version: "3.7"

services:
  app:
    build:
      context: .
    command:
      sh -c "python tgbot.py"
    container_name: app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370