version: "3.7"

services:
  app:
    build:
      context: .

    container_name: app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    ports:
      - 5370:5370